<?php

/**
 * PluginTweetHashtagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTweetHashtagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTweetHashtagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTweetHashtag');
    }
}