<?php

/**
 * PluginRetweetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginRetweetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginRetweetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginRetweet');
    }
}