<?php

/**
 * PluginTwitterSearchPhraseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTwitterSearchPhraseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTwitterSearchPhraseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTwitterSearchPhrase');
    }
}