<?php

/**
 * PluginMediaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMediaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMediaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMedia');
    }
}