<?php

/**
 * PluginLinkTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLinkTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginLinkTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginLink');
  }

  public function findOneByUrl($url)
  {
    return $this->findOneByHash(sha1($url));
  }
}