<?php

/**
 * PluginTweetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTweetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTweetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTweet');
    }
}