<?php

/**
 * PluginTweetSourceTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTweetSourceTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginTweetSourceTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginTweetSource');
  }

  public function findOneBySource($source)
  {
    return $this->findOneByHash(sha1($source));
  }
}