<?php

/**
 * PluginTweet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginTweet extends BaseTweet
{
  /**
   * creates Tweet object from std object
   * @param Standard Object $t - object retrieved from json_decode
   * @see json_decode
   * @return Tweet object
   */
  // static public function hydrateFromDecodedResponse($t)
  // {
  //   $tweet = new Tweet();
  //   $tweet['tweet_id']        = $t->id                ? $t->id : false;
  //   $tweet['twitter_user_id'] = $t->user->id          ? $t->user->id : false;
  //   $tweet['screen_name']     = $t->user->screen_name ? $t->user->screen_name : false;
  //   $tweet['body']            = $t->text              ? $t->text : false;
  //   return $tweet;
  // }

  /**
   * @see in_array
   * @param string $k - the full URL string
   * @param array $arr - the collection of allowed URLs
   * @return boolean
   */
  static private function inArray($k,$arr)
  {
    $url = parse_url($k);
    return is_array($url) && array_key_exists('host', $url) && in_array($url['host'],$arr);
  }

}