<?php

/**
 * PluginHashtagTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginHashtagTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginHashtagTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginHashtag');
  }

  public function findOneByHashtag($hashtag)
  {
    $hashed = sha1($hashtag);
    
    return self::findOneByHash($hashed);
  }

  public function getTrackedQuery()
  {
    return $this->createQuery('h')->where('h.track = ?',true);
  }

  public function getTracked()
  {
    return $this->getTrackedQuery()->execute();
  }
}