<?php

/**
 * PluginTwitterUserSkeletonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTwitterUserSkeletonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTwitterUserSkeletonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTwitterUserSkeleton');
    }
}