<?php

/**
 * PluginTweetMediaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTweetMediaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTweetMediaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTweetMedia');
    }
}