<?php

/**
 * PluginTaskLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTaskLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTaskLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTaskLog');
    }
}