<?php

/**
 * PluginTweetMentionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTweetMentionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTweetMentionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTweetMention');
    }
}