TwitterSearchPhrase:
  columns:
    phrase:             { type: string(140) }
    
  indexes:
    phrase:
      fields:    [ phrase ]
      unique:    true


TwitterUserSkeleton:
  columns:
    id:                           { type: integer, unsigned: true, notnull: true, fixed: true, primary: true }
    screen_name:                  string(16)
    name:                         string(50)
    profile_background_tile:      string
    protected:                    boolean
    verified:                     boolean
    profile_sidebar_fill_color:   { type: string(6), fixed: true }
    profile_sidebar_border_color: { type: string(6), fixed: true }
    profile_image_url:            string
    profile_background_image_url: string
    profile_background_color:     { type: string(6), fixed: true }
    profile_link_color:           { type: string(6), fixed: true }
    profile_text_color:           { type: string(6), fixed: true }
    lang:                         { type: string(2), fixed: true }
    time_zone:                    string(20)
    utc_offset:                   { type: integer, unsigned: false }
    geo_enabled:                  boolean
    description:                  string(160)
    friends_count:                integer
    followers_count:              integer
    
  actAs:
    Timestampable:                ~
    
  indexes:
    user:
      fields:         [ id, screen_name ]
      type:           unique


Hashtag:
  options:
    symfony:
      form:             false
      
  columns:
    hashtag:                string(140)
    hash:                   { type: string(40), fixed: true }
    track:                  { type: boolean, default: false }
    
  indexes:
    hashed_hashtag:
      fields:               [ hash ]
      type:                 unique
    track_hashtag:
      fields:               [ track ]
      
  actAs:
    Timestampable:
      updated:              { disabled: true }


TweetHashtag:
  options:
    symfony:
      form:   false
      filter: false
      
  columns:
    tweet_id:               { type: integer, unsigned: true, notnull: true, fixed: true, primary: true }
    hashtag_id:             { type: integer, primary: true }


Link:
  options:
    symfony:
      form:   false
      
  columns:
    url:                    string
    display_url:            string
    expanded_url:           string
    hash:                   { type: string(40), fixed: true }
    
  actAs:
    Timestampable:
      updated:              { disabled: true }
      
  indexes:
    url_hash:
      fields:               [ hash ]
      type:                 unique
    link_created_at:
      fields:               [ created_at ]


TweetLink:
  options:
    symfony:
      form:   false
      filter: false
      
  columns:
    tweet_id:               { type: integer, unsigned: true, notnull: true, fixed: true, primary: true }
    link_id:                { type: integer, primary: true }


Media:
  options:
    symfony:
      form:   false
      
  columns:
    id:                     { type: integer, unsigned: true, notnull: true, primary: true }
    type:                   string(30)
    media_url:              string   # append :thumb, :large, :medium, :small to end to get the different sizes, medium by default
    media_url_https:        string
    url:                    string
    display_url:            string
    expanded_url:           string
    sizes:                  array(1000)
    hash:                   { type: string(40), fixed: true }
    
  actAs:
    Timestampable:
      updated:              { disabled: true }
      
  indexes:
    url_hash:
      fields:               [ hash ]
      type:                 unique
    link_created_at:
      fields:               [ created_at ]


TweetMedia:
  options:
    symfony:
      form:   false
      filter: false
      
  columns:
    tweet_id:               { type: integer, unsigned: true, notnull: true, fixed: true, primary: true }
    media_id:               { type: integer, unsigned: true, notnull: true, primary: true }


TweetSource:
  columns:
    source:                 text
    hash:                   { type: string(40), fixed: true }
    
  indexes:
    source_hash:
      fields:               [ hash ]
      type:                 unique
      
  options:
    symfony:
      form:             false


Tweet:
  options:
    symfony:
      form:             false
      
  actAs:
    Timestampable:     ~
    
  columns:
    id:                     { type: integer, unsigned: true, notnull: true, primary: true, fixed: true }
    text:                   { type: string(140), fixed: true }
    in_reply_to_user_id:    { type: integer, unsigned: true, notnull: false, fixed: true }
    in_reply_to_status_id:  { type: integer, unsigned: true, notnull: false, fixed: true }
    retweet_count:          integer
    retweeted:              boolean
    favorited:              boolean
    truncated:              boolean
    user_id:                { type: integer, unsigned: true, notnull: false, fixed: true }
    source_id:              integer
    place_id:               { type: string(20), fixed: true }
    twitter_id:             integer
  
  indexes:
    tweet_text:
      fields:               [ text ]
            
  relations:
    Author:
      alias:                Author
      local:                user_id
      foreign:              id
      class:                TwitterUserSkeleton
      type:                 one
      foreignType:          many
    InReplyTo:
      local:                in_reply_to_status_id
      foreign:              id
      type:                 one
      class:                Tweet
      foreignAlias:         Replies
    Hashtags:
      class:                Hashtag
      refClass:             TweetHashtag
      local:                tweet_id
      foreign:              hashtag_id
      onDelete:             cascade
    Source:
      class:                TweetSource
      local:                source_id
      foreign:              id
    URLs:
      class:                Link
      refClass:             TweetLink
      local:                tweet_id
      foreign:              link_id
      onDelete:             cascade
    Media:
      class:                Media
      refClass:             TweetMedia
      local:                tweet_id
      foreign:              media_id
      onDelete:             cascade
    RetweetedBy:
      class:                TwitterUserSkeleton
      refClass:             Retweet
      local:                tweet_id
      foreign:              retweeter_id
      alias:                RetweetedBy
      foreignAlias:         Retweets
    Mentions:
      class:                TwitterUserSkeleton
      refClass:             TweetMention
      local:                tweet_id
      foreign:              follower_id
      alias:                Mentions
      foreignAlias:         MentionedIn


Retweet:
  options:
    symfony:
      filter: false
      form:   false
      
  columns:
    tweet_id:               { type: integer, unsigned: true, notnull: true, primary: true, fixed: true }
    retweeter_id:           { type: integer, unsigned: true, notnull: true, primary: true, fixed: true }
    
  relations:
    Tweet:
      foreignAlias:         Retweets
      
  actAs:
    Timestampable:
      updated:              { disabled: true }
      
  indexes:
    retweet:
      fields:               [ tweet_id, retweeter_id ]
      type:                 unique
    retweeted_at:
      fields:               [ created_at ]


TweetMention:
  columns:
    tweet_id:               { type: integer, unsigned: true, notnull: true, primary: true, fixed: true }
    follower_id:            { type: integer, unsigned: true, notnull: true, primary: true, fixed: true }
    
  options:
    symfony:
      form:             false
      filter:           false


TaskLog:
  actAs:
    Timestampable:
      updated:          { disabled: true }
        
  options:
    symfony:
      form:             false
      filter:           false
      
  columns:
    message:            { type: text, notnull: true }
